version: "3.8"

x-logging:
  &loki-logging
  driver: loki
  options:
    loki-url: "http://10.100.126.2:3100/loki/api/v1/push"
    loki-batch-size: "400"
    loki-retries: "2"
    loki-timeout: "1s"
    loki-max-backoff: "800ms"
    keep-file: "true"
    max-size: "50m"
    max-file: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8080:80"
    volumes:
      # Optional: Falls du während der Entwicklung Änderungen direkt mounten möchtest
      # - ./build/web:/usr/share/nginx/html:ro
      - ./download:/usr/share/nginx/html/download:ro
    logging: *loki-logging

  backend:
    build:
      context: ./api_backend
      dockerfile: Dockerfile.backend
    ports:
      - "3009:3009"
    volumes:
      - ./api_backend:/usr/src/app:cached
      # - /usr/src/app/node_modules
    environment:
      - NODE_ENV=production
      - API_TOKEN=${API_TOKEN}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
    logging: *loki-logging