version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8080:80"
    volumes:
      # Optional: Falls du während der Entwicklung Änderungen direkt mounten möchtest
      - ./build/web:/usr/share/nginx/html:ro
