FROM node:18-bullseye

# Setze die Zeitzone auf Europe/Zurich
ENV TZ=Europe/Zurich
RUN apt-get update && apt-get install -y tzdata && \
    ln -sf /usr/share/zoneinfo/$TZ /etc/localtime && \
    echo $TZ > /etc/timezone && \
    apt-get clean

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 3009
CMD ["npm", "start"]
